version: '3.7'

services:
  app: &app
    build:
      context: .
      target: build
    image: multi-lang
    volumes:
      - .:/app

  lint:
    image: multi-lang
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "cd app && poetry run python -m pylint *"
